[phases.setup]
nixPkgs = [
    "php84",
    "php84Packages.composer",
    "php84Extensions.pdo_sqlite",
    "php84Extensions.fileinfo",
    "php84Extensions.mbstring",
    "php84Extensions.openssl",
    "php84Extensions.tokenizer",
    "php84Extensions.xml",
    "php84Extensions.dom",
    "php84Extensions.filter",
    "php84Extensions.session",
    "php84Extensions.ctype",
    "php84Extensions.curl",
    "php84Extensions.iconv",
    "php84Extensions.intl",
    "php84Extensions.zip",
    "php84Extensions.bcmath",
    "php84Extensions.simplexml",
    "nodejs_22"
]

[phases.build]
cmds = [
    "mkdir -p storage/framework/{sessions,views,cache}",
    "mkdir -p storage/logs",
    "mkdir -p database",
    "touch database/database.sqlite",
    "composer install --no-dev --optimize-autoloader --no-interaction",
    "npm install",
    "npm run build",
    "php artisan storage:link"
]

[start]
cmd = "chmod -R 777 storage bootstrap/cache database && php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=$PORT"
